version: '2.1'
services:
  faucet:
    container_name: filecoin-verifier-service
    build: ./
    ports:
      - 3001:3001
    environment:
      NODE_ENV: 'localhost'
     
networks:
  default:
    external:
      name: verifier_service
